# 划分train和test

In [41]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [70]:
pass_path = "../data/labeled_data/0_PASS/0_PASS.xlsx"
fail_path = "../data/labeled_data/1_FAIL/1_FAIL.xlsx"
# un_path = "../data/labeled_data/1_FAIL/1_FAIL.xlsx"

df_pass = pd.read_excel(pass_path)
df_fail = pd.read_excel(fail_path)
# df_un = pd.read_excel(un_path)

In [72]:
df_pass["before_1"] = "/img/" + df_pass["ID"] + "/before_1.png"
df_pass["before_2"] = "/img/" + df_pass["ID"] + "/before_2.png"
df_pass["before_3"] = "/img/" + df_pass["ID"] + "/before_3.png"

df_pass["after_1"] = "/img/" + df_pass["ID"] + "/after_1.png"
df_pass["after_2"] = "/img/" + df_pass["ID"] + "/after_2.png"
df_pass["after_3"] = "/img/" + df_pass["ID"] + "/after_3.png"

In [74]:
df_fail["before_1"] = "/img/" + df_fail["ID"] + "/before_1.png"
df_fail["before_2"] = "/img/" + df_fail["ID"] + "/before_2.png"
df_fail["before_3"] = "/img/" + df_fail["ID"] + "/before_3.png"

df_fail["after_1"] = "/img/" + df_fail["ID"] + "/after_1.png"
df_fail["after_2"] = "/img/" + df_fail["ID"] + "/after_2.png"
df_fail["after_3"] = "/img/" + df_fail["ID"] + "/after_3.png"

In [76]:
random_state = 42
pass_train, pass_test = train_test_split(
    df_pass, 
    test_size = 0.2,
    random_state = random_state
)

In [78]:
fail_train, fail_test = train_test_split(
    df_fail, 
    test_size = 0.2,
    random_state = random_state
)

In [80]:
df_train = pd.concat([pass_train, fail_train], ignore_index=True)
df_test = pd.concat([pass_test, fail_test], ignore_index=True)

In [82]:
df_train = df_train.sample(frac=1, random_state=random_state).reset_index(drop=True)
df_test = df_test.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [84]:
df_train.head()

,ID,consistency,reason,color,shape,occlusion,reappearance_time,before_1,before_2,before_3,after_1,after_2,after_3,清晰度评分（1–5）,流畅度评分（1–5）,before_color,after_color,before_shape,after_shape,Unnamed: 9
0,C0033,0,浅绿色球在挡板右侧重现，颜色、球形及大小基本一致。,浅绿色→浅绿色,球体→球体,2.1,2.7,/img/C0033/before_1.png,/img/C0033/before_2.png,/img/C0033/before_3.png,/img/C0033/after_1.png,/img/C0033/after_2.png,/img/C0033/after_3.png,5,5,35,35,1,1,NaN
1,C0066,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,绿色→绿色,球体→球体,1.9,2.7,/img/C0066/before_1.png,/img/C0066/before_2.png,/img/C0066/before_3.png,/img/C0066/after_1.png,/img/C0066/after_2.png,/img/C0066/after_3.png,3,4,3,3,1,1,NaN
2,C0192,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,浅黄色→浅黄色,球形→球形,2.2,4.0,/img/C0192/before_1.png,/img/C0192/before_2.png,/img/C0192/before_3.png,/img/C0192/after_1.png,/img/C0192/after_2.png,/img/C0192/after_3.png,3,4,40,40,76,76,NaN
3,C0324,1,左侧原圆盘尚未完全进入时右侧已出现另一圆盘，同一时刻两侧均可见，数量及遮挡衔接异常。,黑色→黑色,一个圆盘→两个圆盘,1.6,1.6,/img/C0324/before_1.png,/img/C0324/before_2.png,/img/C0324/before_3.png,/img/C0324/after_1.png,/img/C0324/after_2.png,/img/C0324/after_3.png,5,4,9,9,6,13,NaN
4,C0255,0,两球进入隧道后从相对侧重现，颜色、球形及数量基本一致；透视导致表观大小不同。,青蓝色、灰色→青蓝色、灰色,两个球体→两个球体,1.6,2.8,/img/C0255/before_1.png,/img/C0255/before_2.png,/img/C0255/before_3.png,/img/C0255/after_1.png,/img/C0255/after_2.png,/img/C0255/after_3.png,4,5,96,96,18,18,NaN

In [86]:
df_test.head()

,ID,consistency,reason,color,shape,occlusion,reappearance_time,before_1,before_2,before_3,after_1,after_2,after_3,清晰度评分（1–5）,流畅度评分（1–5）,before_color,after_color,before_shape,after_shape,Unnamed: 9
0,C0495,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,青蓝色→青蓝色,球形→球形,1.7,2.8,/img/C0495/before_1.png,/img/C0495/before_2.png,/img/C0495/before_3.png,/img/C0495/after_1.png,/img/C0495/after_2.png,/img/C0495/after_3.png,5,4,92,92,76,76,NaN
1,C0356,0,经轨道及中央挡板遮挡后重现，可见属性基本一致。,紫红色→紫红色,球形→球形,3.0,3.1,/img/C0356/before_1.png,/img/C0356/before_2.png,/img/C0356/before_3.png,/img/C0356/after_1.png,/img/C0356/after_2.png,/img/C0356/after_3.png,3,3,63,63,76,76,NaN
2,C0471,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,蓝色、棕色→蓝色、棕色,方块、球体→方块、球体,1.1,4.2,/img/C0471/before_1.png,/img/C0471/before_2.png,/img/C0471/before_3.png,/img/C0471/after_1.png,/img/C0471/after_2.png,/img/C0471/after_3.png,4,4,81,81,64,64,NaN
3,C0115,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,银灰色→银灰色,小球形摆锤→小球形摆锤,0.9,1.5,/img/C0115/before_1.png,/img/C0115/before_2.png,/img/C0115/before_3.png,/img/C0115/after_1.png,/img/C0115/after_2.png,/img/C0115/after_3.png,5,5,85,85,45,45,NaN
4,C0482,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,绿色（含亮色纹理）→绿色（含亮色纹理）,球形→球形,1.2,2.9,/img/C0482/before_1.png,/img/C0482/before_2.png,/img/C0482/before_3.png,/img/C0482/after_1.png,/img/C0482/after_2.png,/img/C0482/after_3.png,3,3,3,3,76,76,NaN

In [88]:
import os
def save_or_update(df, file_path):
    folder = os.path.dirname(file_path)
    if folder:
        os.makedirs(folder, exist_ok=True)
    df.to_excel(file_path, index=False)

In [90]:
train_path = "../data/labeled_data/train/train.xlsx"
test_path = "../data/labeled_data/test/test.xlsx"

In [92]:
save_or_update(df_train, train_path)

In [94]:
save_or_update(df_test, test_path)