In [275]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [277]:
pass_path = "../data/labeled_data/0_PASS/0_PASS.xlsx"
fail_path = "../data/labeled_data/1_FAIL/1_FAIL.xlsx"
# un_path = "../data/labeled_data/1_FAIL/1_FAIL.xlsx"

df_pass = pd.read_excel(pass_path)
df_fail = pd.read_excel(fail_path)
# df_un = pd.read_excel(un_path)

In [283]:
random_state = 42
pass_train, pass_test = train_test_split(
    df_pass, 
    test_size = 0.2,
    random_state = random_state
)

In [285]:
fail_train, fail_test = train_test_split(
    df_fail, 
    test_size = 0.2,
    random_state = random_state
)

In [125]:
un_train, un_test = train_test_split(
    df_un, 
    test_size = 0.2,
    random_state = random_state
)

In [287]:
df_train = pd.concat([pass_train, fail_train], ignore_index=True)
df_test = pd.concat([pass_test, fail_test], ignore_index=True)

In [289]:
df_train = df_train.sample(frac=1, random_state=random_state).reset_index(drop=True)
df_test = df_test.sample(frac=1, random_state=random_state).reset_index(drop=True)

In [291]:
df_train.head()

,ID,consistency,reason,color,shape,occlusion,reappearance_time,before_1,before_2,before_3,after_1,after_2,after_3
0,C0069,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,绿色→绿色,球体→球体,1.6,2.3,/img/C0069/before_1.png,/img/C0069/before_2.png,/img/C0069/before_3.png,/img/C0069/after_1.png,/img/C0069/after_2.png,/img/C0069/after_3.png
1,C0045,1,红球消失后，银灰色球从画面左端重新进入并穿过挡板，颜色改变且位置跳变。,红色→银灰色,球体→球体,1.6,2.5,/img/C0045/before_1.png,/img/C0045/before_2.png,/img/C0045/before_3.png,/img/C0045/after_1.png,/img/C0045/after_2.png,/img/C0045/after_3.png
2,C0034,0,黄色带深色斑块的球在右侧重现，颜色组合、球形及大小基本一致。,黄色带深色斑块→黄色带深色斑块,球体→球体,1.7,3.0,/img/C0034/before_1.png,/img/C0034/before_2.png,/img/C0034/before_3.png,/img/C0034/after_1.png,/img/C0034/after_2.png,/img/C0034/after_3.png
3,C0152,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,青蓝色→青蓝色,立方体→立方体,2.5,3.5,/img/C0152/before_1.png,/img/C0152/before_2.png,/img/C0152/before_3.png,/img/C0152/after_1.png,/img/C0152/after_2.png,/img/C0152/after_3.png
4,C0205,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,青蓝色→青蓝色,球形→球形,2.0,2.9,/img/C0205/before_1.png,/img/C0205/before_2.png,/img/C0205/before_3.png,/img/C0205/after_1.png,/img/C0205/after_2.png,/img/C0205/after_3.png

In [221]:
df_test.head()

,ID,consistency,reason,color,shape,occlusion,reappearance_time,before_1,before_2,before_3,after_1,after_2,after_3
0,C0264,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,青蓝色、灰色→青蓝色、灰色,两个球体→两个球体,1.4,2.7,/img/C0264/before_1.png,/img/C0264/before_2.png,/img/C0264/before_3.png,/img/C0264/after_1.png,/img/C0264/after_2.png,/img/C0264/after_3.png
1,C0356,0,经轨道及中央挡板遮挡后重现，可见属性基本一致。,紫红色→紫红色,球形→球形,3.0,3.1,/img/C0356/before_1.png,/img/C0356/before_2.png,/img/C0356/before_3.png,/img/C0356/after_1.png,/img/C0356/after_2.png,/img/C0356/after_3.png
2,C0495,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,青蓝色→青蓝色,球形→球形,1.7,2.8,/img/C0495/before_1.png,/img/C0495/before_2.png,/img/C0495/before_3.png,/img/C0495/after_1.png,/img/C0495/after_2.png,/img/C0495/after_3.png
3,C0580,0,首轮遮挡后三目标完整重现，颜色形状基本一致；末段再次关闭时结束，后一次遮挡未完成。,紫色、蓝色、绿色→紫色、蓝色、绿色,球体、方块、棱锥→球体、方块、棱锥,0.7,2.4,/img/C0580/before_1.png,/img/C0580/before_2.png,/img/C0580/before_3.png,/img/C0580/after_1.png,/img/C0580/after_2.png,/img/C0580/after_3.png
4,C0485,0,目标经遮挡后重现，可见颜色、形状、大小和数量基本一致。,绿色→绿色,球形→球形,1.1,3.2,/img/C0485/before_1.png,/img/C0485/before_2.png,/img/C0485/before_3.png,/img/C0485/after_1.png,/img/C0485/after_2.png,/img/C0485/after_3.png

In [293]:
import os
def save_or_update(df, file_path):
    folder = os.path.dirname(file_path)
    if folder:
        os.makedirs(folder, exist_ok=True)
    df.to_excel(file_path, index=False)

In [295]:
train_path = "../data/labeled_data/train/train.xlsx"
test_path = "../data/labeled_data/test/test.xlsx"

In [297]:
save_or_update(df_train, train_path)

In [299]:
save_or_update(df_test, test_path)

In [279]:
df_pass["before_1"] = "/img/" + df_pass["ID"] + "/before_1.png"
df_pass["before_2"] = "/img/" + df_pass["ID"] + "/before_2.png"
df_pass["before_3"] = "/img/" + df_pass["ID"] + "/before_3.png"

df_pass["after_1"] = "/img/" + df_pass["ID"] + "/after_1.png"
df_pass["after_2"] = "/img/" + df_pass["ID"] + "/after_2.png"
df_pass["after_3"] = "/img/" + df_pass["ID"] + "/after_3.png"

In [281]:
df_fail["before_1"] = "/img/" + df_fail["ID"] + "/before_1.png"
df_fail["before_2"] = "/img/" + df_fail["ID"] + "/before_2.png"
df_fail["before_3"] = "/img/" + df_fail["ID"] + "/before_3.png"

df_fail["after_1"] = "/img/" + df_fail["ID"] + "/after_1.png"
df_fail["after_2"] = "/img/" + df_fail["ID"] + "/after_2.png"
df_fail["after_3"] = "/img/" + df_fail["ID"] + "/after_3.png"